[env]
CACHE_DIR = "./cache"
PROMPTS_JSON = "./helpers/prompts.json"

[llm]
TOGETHER_API_KEY = "e38fa712fc3270e8f6945048dcaf23ac84f0152e94ba66c0467d5faeb038a144"
EMBEDDING_MODEL = "sentence-transformers/msmarco-bert-base-dot-v5"
OPENAI_API_KEY = "sk-proj-zBDBubz9dFKcGZ1qPFvLT3BlbkFJwSKsKtinHpAga7No8tML"
HUGGINGFACE_API_KEY = "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"
GEMINI_API_KEY = "AIzaSyAmvCTCDF3l3iaoEUIUQ92t_ykqxHOfXwg"

[db]
MONGO_URI = "mongodb+srv://root:root@stocksearch.bdg01rx.mongodb.net/?retryWrites=true&w=majority&appName=stocksearch"
MONGO_DB = "teach_it"
MONGO_COLLECTION="corpora"
REDIS_HOST = "redis-17597.c267.us-east-1-4.ec2.redns.redis-cloud.com"
REDIS_PORT = "17597"
REDIS_PASSWORD = "qf7DxqEI8JRkxpL7luBsvrTn2ozX6FgF"
CLOUDINARY_APP_NAME = "dmr4n68im"
CLOUDINARY_API_KEY = "287928376286386"
CLOUDINARY_API_SECRET = "3cmUgBdb1Am1iiB3nqbGAt3m8j4"

[hugging_face_urls]
TTS_URL = "https://api-inference.huggingface.co/models/microsoft/speecht5_tts"
MUSIC_GEN_URL = "https://api-inference.huggingface.co/models/facebook/musicgen-small"
AVL_URL="https://api-inference.huggingface.co/models/RavenOnur/Sign-Language"
